name: Coverage

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      #  with:
      #    submodules: recursive
      #    fetch-depth: 0
      - uses: goto-bus-stop/setup-zig@v2
      - name: Install kcov (Linux)
        if: startsWith(matrix.runs-on, 'ubuntu')
        run: sudo apt install -y kcov

      - name: Install kcov (MacOS)
        if: startsWith(matrix.runs-on, 'macos')
        run: brew install kcov

      - name: Coverage
        run: zig build coverage
