name: Coverage

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
      - name: Install kcov
        run: sudo apt install -y kcov

      - name: Generate Coverage
      #  run: zig build coverage -DcoverallsId=${{ secrets.COVERALLS_REPO_TOKEN }}
        run: zig build coverage

      - name: Coveralls
        uses: coverallsapp/github-action@v2
