name: Coverage

on:
  push:
    branches: [ "mains" ]

jobs:
  coverage:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
      - name: Install kcov
        run: sudo apt install -y kcov

      - name: Generate Coverage
        run: zig build coverage

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./.coverage/
          fail_ci_if_error: true
